{% set name = "xxHash" %}
{% set version = "0.7.4" %}
{% set sha256 = "4d9706c9da4fbdf901598f5e3b71db0eddd4ac962e827a73ebf75d66dfd820fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Cyan4973/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - xxhsum --help

about:
  home: http://www.xxhash.com/
  license: BSD
  license_file: {{ environ["SRC_DIR"] }}/LICENSE
  summary: Extremely fast hash algorithm
  description: |
    xxHash is an Extremely fast Hash algorithm, running at RAM speed limits. It
    successfully completes the SMHasher test suite which evaluates collision,
    dispersion and randomness qualities of hash functions. Code is highly
    portable, and hashes are identical on all platforms (little / big endian).
  dev_url: https://github.com/Cyan4973/xxHash
  doc_url: https://github.com/Cyan4973/xxHash

extra:
  recipe-maintainers:
    - beckermr
