appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: p7hsqpJvnitG2XtDYR3Z8bHu9Wvv+wbc/5Zp5GDc84jJawnstxlioBt3ud6I8n0BsnVIAfn3JHIGt6eAH8IeYCrkpb/NmtDd0Ob2VyFgFtWRrfsv5hmtWhAR9TzWjxpcxsLbwTrIyWiDu/U4oK/cz7gxDN8WLR1zLANYbyTTuY2NJMTKWac0btByTVdQorJjnhg28Ze+ZC450cPfRw+mOuLEL6y+3f2Ih6AkwVxOEFTd5FstM8k7n0wbHTrZaVmeTNg7Tvm50wwfrBvK5LF5Hg0bqxJsUHbDIUiDnpvRql1lgqaT8LBNLlKjpFDe32k3HHqyR9qjM6bSB0oXThTNDIR0fiB7KFIGbonYC4OE/uNEVkmjh2pn1XgHtSAtJMpTqko5xQMBlDY4OOQbSg4aRsXiLN97qyi6zHFBD8mnCdUePRtWuBBG+J3tEVaDdUqrlfncOUfArn9d162Hs/uzp19a1qBsU7bE4nvIb5iii+curKiwCPcTQl5lVbum8HNRoH9GVO5V39k7VtRJx3zNIkcP3X4DKjS0v4/7FpTkL4VVnd2L4GBROYAB67mIj+7zAA71tNeCBci1fk8mjWXzduDPCtB8uZzgPsIMem5CP2mdmGABO194NgGnD9A6ov2+t36jvRcXWQYXNFICg1Ex1s9CTrTq2EMABu/piNifCzU=}
